// <auto-generated />
using System;
using ErpClink.Modules.Queue.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpClink.Modules.Queue.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QueueDbContext))]
    [Migration("20260913133318_AddQueueModule")]
    partial class AddQueueModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("queue")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpClink.Modules.Queue.Domain.Entries.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CalledTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date");

                    b.Property<string>("QueueNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("ServiceEndTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ServiceStartTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("OrganizationId", "AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_QueueEntries_ActiveAppointment")
                        .HasFilter("[Status] IN ('Waiting', 'Called', 'InService')");

                    b.HasIndex("OrganizationId", "ClinicId", "QueueDate");

                    b.HasIndex("OrganizationId", "DoctorId", "QueueDate");

                    b.HasIndex("OrganizationId", "PatientId", "QueueDate");

                    b.HasIndex("OrganizationId", "BranchId", "QueueDate", "Status");

                    b.HasIndex("OrganizationId", "BranchId", "QueueDate", "ClinicId", "QueueNumber")
                        .IsUnique();

                    b.ToTable("QueueEntries", "queue");
                });

            modelBuilder.Entity("ErpClink.Modules.Queue.Infrastructure.Persistence.QueueNumberSequence", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId", "BranchId", "ClinicId", "QueueDate");

                    b.ToTable("QueueNumberSequences", "queue");
                });
#pragma warning restore 612, 618
        }
    }
}
